repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-executables-have-shebangs
    #-   id: check-shebang-scripts-are-executable
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/executablebooks/mdformat
    rev: 0.7.5
    hooks:
    -   id: mdformat
