site_name: Keiran M Raine M.Sc.
theme:
  name: material
  logo: ./images/profile.jpg
  palette:
    primary: blue grey
  favicon: images/favicon32c256.png
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/keiranmraine
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/keiranmraine
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/keiranraine/
